name: Bug report
description: Submit a bug report
title: "[BUG] "
labels: TRIAGE
body:
  - type: markdown
    attributes:
      value: "# Bug report"
  - type: markdown
    attributes:
      value: Thank you for reporting a bug and helping us improve cuPyNumeric!
  - type: markdown
    attributes:
      value: >
        Please fill out all of the required information.
  - type: markdown
    attributes:
      value: |
        ---
        ## Environment information
  - type: textarea
    id: legate_issue
    attributes:
      label: Software versions
      description: >-
        Run `legate-issue` and paste the output here.
      placeholder: |
        Python      :  3.12.4 | packaged by conda-forge | (main, Jun 17 2024, 10:23:07) [GCC 12.3.0]
        Platform    :  Linux-6.8.0-40-generic-x86_64-with-glibc2.35
        Legion      :  (failed to detect)
        Legate      :  24.05.00+255.g2656afbd
        cuPynumeric :  24.05.00+132.gc4741d57
        Numpy       :  1.26.4
        Scipy       :  1.13.1
        Numba       :  (failed to detect)
        CTK package :  cuda-version-12.0-hffde075_3 (conda-forge)
        GPU driver  :  535.183.06
        GPU devices :
          GPU 0: NVIDIA RTX A5000
          GPU 1: NVIDIA RTX A5000
    validations:
      required: true
  - type: input
    id: jupyter
    attributes:
      label: Jupyter notebook / Jupyter Lab version
      description: >-
        Please supply if the issue you are reporting is related to Jupyter
        notebook or Jupyter Lab.
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ## Issue details
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: observed-behavior
    attributes:
      label: Observed behavior
      description: What did actually happen?
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Directions to reproduce
  - type: textarea
    id: example
    attributes:
      label: Example code or instructions
      description: >
        Please provide detailed instructions to reproduce the issue. Ideally this includes a
        [Complete, minimal, self-contained example code](https://stackoverflow.com/help/minimal-reproducible-example)
        given here or as a link to code in another repository.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Additional information
  - type: textarea
    id: traceback-console
    attributes:
      label: Stack traceback or browser console output
      description: >
        Add any error messages or logs that might be helpful in reproducing and
        identifying the bug, for example a Python stack traceback.
    validations:
      required: false
