#!/usr/bin/env bash

generate_legate_version() {
    if ! command -v jq &> /dev/null; then
        apt-get -qq update >/dev/null
        apt-get -qq install -y jq >/dev/null
    fi

    legate_json_version="$(jq -r '.packages.legate.version' "${REPO_DIR}/cmake/versions.json")";
    legate_SHA="$(jq -r '.packages.legate.git_tag' "${REPO_DIR}/cmake/versions.json")";
    legate_hash="g${legate_SHA:0:8}"
    export LEGATE_VERSION="${legate_json_version}*"
    export LEGATE_BUILDSTR="*${legate_hash}*"
    echo "LEGATE_VERSION=${LEGATE_VERSION} : LEGATE_BUILDSTR=${LEGATE_BUILDSTR}"
}
