#!/usr/bin/env bash

set -x

. conda-utils

make_release_env() {
    mamba create -q -y -n "${CONDA_ENV}" -c conda-forge boa
}

make_conda_env() {
    set -xeuo pipefail

    case "$1" in
        ci) make_release_env;;
        nightly) make_release_env;;
        *) return 1;;
    esac

    return 0;
}

(make_conda_env "$@");
