#!/usr/bin/env bash

. conda-utils

make_release_env() {
    legate-conda-retry create -q -y -n "${CONDA_ENV}" -c conda-forge boa
}

make_docs_env() {
    set -euo pipefail

    export DEBIAN_FRONTEND=non-interactive
    export CONDA_ENV=legate

    # Run package updates and install packages
    apt-get -qq update >/dev/null
    apt-get -qq install -y numactl make >/dev/null

    legate-conda-retry create -yn "${CONDA_ENV}" pandoc doxygen pip

    . conda-utils;
    activate_conda_env;
    hash -r

    # mamba install -y pandoc doxygen
    python -m pip install \
        --disable-pip-version-check \
        ipython jinja2 "markdown<3.4.0" myst-parser nbsphinx \
        sphinx-copybutton "sphinx>=8" nvidia-sphinx-theme cffi
}

make_conda_env() {
    set -euo pipefail

    case "$1" in
        ci) make_release_env;;
        nightly) make_release_env;;
        docs) make_docs_env;;
        *) return 1;;
    esac

    return 0;
}

(make_conda_env "$@");
